### ISSUE TITLE
Does this plugin still work with Jenkins 2.20 and new Git plugin 2.5.3?

### ISSUE THREAD

**Issue by joelruns** [ingenieux/codecommit-url-helper#2] opened 2016-08-31 02:51 UTC
This plugin seems to do nothing in new Jenkins. I cannot add the AWS Credential ID as instructed on the Jenkins plugin page. When I add the behavior it looks as follows on my Jenkins project configuration page. Is this right?

![screen shot 2016-08-30 at 10 38 12 pm](https://cloud.githubusercontent.com/assets/5619611/18114305/2ed6ae1e-6f04-11e6-9d79-1a16f2af6462.png)

**Comment by aldrinleal** [comment] 2016-08-31 03:35
Interesting. Never seen that. I'll go take a look. Meanwhile: Anything fancy on your jenkins logs?

**Comment by joelruns** [comment] 2016-08-31 14:15
Apologies I passed out early last night. What I see in `/var/log/jenkins/jenkins.log` is just regarding installation.

```
INFO: Jenkins is fully up and running
Aug 31, 2016 2:22:01 AM hudson.model.UpdateCenter$DownloadJob run
INFO: Starting the installation of AWS CodeCommit URL Helper on behalf of admin
Aug 31, 2016 2:22:01 AM hudson.model.UpdateCenter$UpdateCenterConfiguration download
INFO: Downloading AWS CodeCommit URL Helper
Aug 31, 2016 2:22:02 AM hudson.PluginManager dynamicLoad
INFO: Attempting to dynamic load /var/lib/jenkins/plugins/codecommit-url-helper.jpi
[Some jenkins.InitReactorRunner$1 lines that were successful]
Aug 31, 2016 2:22:02 AM hudson.PluginManager dynamicLoad
INFO: Plugin codecommit-url-helper:0.0.1 dynamically installed
Aug 31, 2016 2:22:02 AM hudson.model.UpdateCenter$DownloadJob run
INFO: Installation successful: AWS CodeCommit URL Helper
```

I'm viewing the page in Safari, not sure if that makes a difference, but the HTML doesn't seem to show there exists any fields to fill in.
![screen shot 2016-08-31 at 10 13 11 am](https://cloud.githubusercontent.com/assets/5619611/18132142/95c96f62-6f63-11e6-8d8d-ee3e0f7df6cb.png)
I'll try looking at it on Chrome and maybe it'll make a difference.

**Comment by joelruns** [comment] 2016-08-31 14:39
Seems to be the same on Chrome.
![screen shot 2016-08-31 at 10 27 29 am](https://cloud.githubusercontent.com/assets/5619611/18133087/361a0bfe-6f67-11e6-8e6a-8fb3854a2554.png)

**Comment by joelruns** [comment] 2016-09-01 04:05
Hmm I tried to do some more debugging by starting and stopping Jenkins. No errors and the only warning is empty contextPath. Hmm does it work for you on new Jenkins?

**Comment by kindermax** [comment] 2016-12-07 14:51
Hi. I tried to add this line \<input name="credentialId" class="setting-input" value="<your_credential_id>" type="text"\> to the html code.
![codecommit5](https://cloud.githubusercontent.com/assets/10552804/20972351/41ce157a-bc9d-11e6-83ac-8a900817cc9d.png)
So i got a text field and put my credentialid and click save. And it works. Do you have any ideas why credentialid text field does not exists when page is loaded ?

**Comment by mgetto** [comment] 2016-12-22 09:32
I have the same issue. Really hope the plugin will be fixed soon.

@kindritskyiMax thanks for the workaround. Adding the HTML manually works for me too.

**Comment by snowfire20** [comment] 2018-08-16 15:00
I also have the same issue, causing major headaches.
we have to remember to edit and add this to the definition every time we make a change to our builds.
Is this plugin no longer maintained?
Is there an alternative plugin we can use?

**Comment by aldrinleal** [comment] 2018-08-16 17:43
@snowfire20 It is still maintainted. I'll look into it :)

**Comment by aldrinleal** [comment] 2018-08-17 20:59
I'll push a new version which requires Git 3.9.1 and aws-credentials 1.23. I was able to reproduce this bug, but the main reason it failed to me was due to using outdated versions of the plugins. Could you guys check it?

**Comment by aldrinleal** [comment] 2018-08-19 00:25
Hah. Check 0.0.3 in a couple hours, ok? 

(Somehow, my pom.xml was not copying the .jelly and .html files to the jar/hpi combo - my bad)

**Closed as completed by aldrinleal** 2018-08-19 00:25 UTC

**Comment by snowfire20** [comment] 2018-08-20 12:47
Adrin,
I've updated the plugin to 0.0.3. we are using git 3.9.1, aws 1.23, and jenkins 2.136 (upgrading later this week).
the build now shows a dropdown for the aws credentials, however they don't re-load when editing the build, none is always the selected option. the builds connect to code commit, so I know it is saving them correctly .
error in dev console:
Uncaught TypeError: Cannot read property 'firstChild' of undefined
    at registerValidator (hudson-behavior.js:424)
    at Array.forEach (<anonymous>)
    at behavior.js:111
    at Array.forEach (<anonymous>)
    at behavior.js:107
    at Array.forEach (<anonymous>)
    at Object.applySubtree (behavior.js:93)
    at select.js:269
